//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatus {
    
    private XCTIPStatusRegister_REQ[] register_REQField;
    
    private XCTIPStatusUnregister_REQ[] unregister_REQField;
    
    private XCTIPStatusRefresh_EV[] refresh_EVField;
    
    private XCTIPStatusChange_EV[] change_EVField;
    
    private XCTIPStatusUpdate_REQ[] update_REQField;
    
    private XCTIPStatusAnswer[] answerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Register_REQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusRegister_REQ[] Register_REQ {
        get {
            return this.register_REQField;
        }
        set {
            this.register_REQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Unregister_REQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusUnregister_REQ[] Unregister_REQ {
        get {
            return this.unregister_REQField;
        }
        set {
            this.unregister_REQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Refresh_EV", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusRefresh_EV[] Refresh_EV {
        get {
            return this.refresh_EVField;
        }
        set {
            this.refresh_EVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Change_EV", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusChange_EV[] Change_EV {
        get {
            return this.change_EVField;
        }
        set {
            this.change_EVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Update_REQ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusUpdate_REQ[] Update_REQ {
        get {
            return this.update_REQField;
        }
        set {
            this.update_REQField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Answer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public XCTIPStatusAnswer[] Answer {
        get {
            return this.answerField;
        }
        set {
            this.answerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusRegister_REQ {
    
    private string cIdField;
    
    private string clearField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CId {
        get {
            return this.cIdField;
        }
        set {
            this.cIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Clear {
        get {
            return this.clearField;
        }
        set {
            this.clearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusUnregister_REQ {
    
    private string cIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CId {
        get {
            return this.cIdField;
        }
        set {
            this.cIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusRefresh_EV {
    
    private string idField;
    
    private string stateField;
    
    private string dndStatField;
    
    private string appStateField;
    
    private string appInfoField;
    
    private string appInfoTimeField;
    
    private string customStateField;
    
    private string cameraField;
    
    private string doorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DndStat {
        get {
            return this.dndStatField;
        }
        set {
            this.dndStatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppState {
        get {
            return this.appStateField;
        }
        set {
            this.appStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfo {
        get {
            return this.appInfoField;
        }
        set {
            this.appInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfoTime {
        get {
            return this.appInfoTimeField;
        }
        set {
            this.appInfoTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomState {
        get {
            return this.customStateField;
        }
        set {
            this.customStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Door {
        get {
            return this.doorField;
        }
        set {
            this.doorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusChange_EV {
    
    private string idField;
    
    private string stateField;
    
    private string dndStatField;
    
    private string appStateField;
    
    private string appInfoField;
    
    private string appInfoTimeField;
    
    private string customStateField;
    
    private string cameraField;
    
    private string doorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DndStat {
        get {
            return this.dndStatField;
        }
        set {
            this.dndStatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppState {
        get {
            return this.appStateField;
        }
        set {
            this.appStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfo {
        get {
            return this.appInfoField;
        }
        set {
            this.appInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfoTime {
        get {
            return this.appInfoTimeField;
        }
        set {
            this.appInfoTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomState {
        get {
            return this.customStateField;
        }
        set {
            this.customStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Camera {
        get {
            return this.cameraField;
        }
        set {
            this.cameraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Door {
        get {
            return this.doorField;
        }
        set {
            this.doorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusUpdate_REQ {
    
    private string cIdField;
    
    private string appStateField;
    
    private string appInfoField;
    
    private string appInfoTimeField;
    
    private string customStateField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CId {
        get {
            return this.cIdField;
        }
        set {
            this.cIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppState {
        get {
            return this.appStateField;
        }
        set {
            this.appStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfo {
        get {
            return this.appInfoField;
        }
        set {
            this.appInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppInfoTime {
        get {
            return this.appInfoTimeField;
        }
        set {
            this.appInfoTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomState {
        get {
            return this.customStateField;
        }
        set {
            this.customStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class XCTIPStatusAnswer {
    
    private string cIdField;
    
    private string errorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CId {
        get {
            return this.cIdField;
        }
        set {
            this.cIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}
